<?xml version="1.0"?>
<robot name="planar_arm" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Properties -->
  <xacro:property name="link_length" value="1"/>
  <xacro:property name="link_radius" value="0.5"/>
  <xacro:property name="joint_limit" value="${pi}"/>

  <!-- Materials -->
  <material name="blue">
    <color rgba="0 0 1 1"/>
  </material>

  <!-- Base Link -->
  <link name="base_link"/>

  <!-- Joint 1 -->
  <joint name="joint1" type="revolute">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-${joint_limit}" upper="${joint_limit}" effort="10" velocity="1"/>
  </joint>

  <link name="link1">
    <visual>
      <origin xyz="${link_length/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${link_length}" radius="${link_radius}"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

  <!-- Joint 2 -->
  <joint name="joint2" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="${link_length} 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-${joint_limit}" upper="${joint_limit}" effort="10" velocity="1"/>
  </joint>

  <link name="link2">
    <visual>
      <origin xyz="${link_length/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${link_length}" radius="${link_radius}"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

  <!-- Joint 3 -->
  <joint name="joint3" type="revolute">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="${link_length} 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-${joint_limit}" upper="${joint_limit}" effort="10" velocity="1"/>
  </joint>

  <link name="link3">
    <visual>
      <origin xyz="${link_length/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${link_length}" radius="${link_radius}"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

  <!-- End Effector -->
  <link name="end_effector">
    <visual>
      <origin xyz="0.1 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </visual>
  </link>

  <joint name="ee_fixed_joint" type="fixed">
    <parent link="link3"/>
    <child link="end_effector"/>
    <origin xyz="${link_length} 0 0" rpy="0 0 0"/>
  </joint>

</robot>
