controller_manager:
  ros__parameters:
    update_rate: 100  # Update rate for controllers
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster  # This broadcasts joint states to ROS

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController  # Trajectory controller for multi-joint control
      joints:
        - joint1
        - joint2
        - joint3
      command_interfaces:
        - position  # Command interface for controlling position
      state_interfaces:
        - position  # State interface to reflect the position of the joints
        - velocity  # State interface for joint velocities
      gains:  # PID gains for controlling each joint
        joint1: {p: 100.0, i: 0.01, d: 10.0}
        joint2: {p: 100.0, i: 0.01, d: 10.0}
        joint3: {p: 100.0, i: 0.01, d: 10.0}
